### ISSUE TITLE
DQ Operators for Bigquery using BQL

### ISSUE THREAD

**Issue by drew-ellingson** [Raybeam/airflow-dq#22]
I've noticed two issues with the current dq operators:

1. Running a DataQualityThresholdCheckOperator task through cloud composer, I get a deprecation warning that parameter 'bql' is being used rather than 'sql'. We should be passing any queries into bigquery using the 'sql' parameter. Relevant [task instance log](https://e3bc769bfa7f35175p-tp.appspot.com/admin/airflow/log?task_id=task_dq_check_pass&dag_id=dq-test-1&execution_date=2020-05-19T17%3A19%3A12.902040%2B00%3A00&format=json)

2. Also, yesterday's PR has 'use_legacy_sql=True' default. It should be false. We want to use standardsql, which allows for dml, subselects, etc. 'use_legacy_sql=True' is the default behavior of the bigquery hook / API that we have to override.

**Comment by drew-ellingson** [comment]
following up on this: the `bql` deprecation is due to an existing bigquery hook code that we didn't write. As long as we can use it for our purposes it probably isn't best to have fix it locally.

Also, the default behavior for `use_legacy_sql` has been changed to `false`

I am trying to verify that I can submit more complex sql (eg. non-legacy) without issues even though we are using `bql`

Currently on running a DQ operator I am getting [this error](https://e3bc769bfa7f35175p-tp.appspot.com/admin/airflow/log?task_id=task_dq_check_pass&dag_id=dq-test-1&execution_date=2020-05-19T21%3A02%3A45.622332%2B00%3A00&format=json) which traces back to [this line](https://github.com/Raybeam/airflow-dq/blob/master/plugins/data_quality_threshold_check_operator.py#L57) edited in yesterday's PR.

@aivu could you take a look?

**Comment by aivu** [comment]
Didn't see this until just now. It is fixed!
